// Generated by scripts/database-types.mjs from the isolated database. Do not edit by hand:
// run `npm run db:types` after a migration, or fix the migration.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string
          actor_player_id: string | null
          created_at: string
          details: Json
          entity_id: string | null
          entity_type: string
          id: string
        }
        Insert: {
          action: string
          actor_player_id?: string | null
          created_at?: string
          details?: Json
          entity_id?: string | null
          entity_type: string
          id?: string
        }
        Update: {
          action?: string
          actor_player_id?: string | null
          created_at?: string
          details?: Json
          entity_id?: string | null
          entity_type?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_player_id_fkey"
            columns: ["actor_player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      automation_alerts: {
        Row: {
          detail: string
          details: Json
          detected_at: string
          id: string
          last_seen_at: string
          notification_attempted_at: string | null
          notification_error: string | null
          notification_recipients: number
          notified_at: string | null
          resolved_at: string | null
          severity: string
          signal_key: string
          title: string
        }
        Insert: {
          detail: string
          details?: Json
          detected_at?: string
          id?: string
          last_seen_at?: string
          notification_attempted_at?: string | null
          notification_error?: string | null
          notification_recipients?: number
          notified_at?: string | null
          resolved_at?: string | null
          severity: string
          signal_key: string
          title: string
        }
        Update: {
          detail?: string
          details?: Json
          detected_at?: string
          id?: string
          last_seen_at?: string
          notification_attempted_at?: string | null
          notification_error?: string | null
          notification_recipients?: number
          notified_at?: string | null
          resolved_at?: string | null
          severity?: string
          signal_key?: string
          title?: string
        }
        Relationships: []
      }
      automation_execution_leases: {
        Row: {
          acquired_at: string
          job_name: string
          locked_until: string
          token: string
        }
        Insert: {
          acquired_at?: string
          job_name: string
          locked_until: string
          token: string
        }
        Update: {
          acquired_at?: string
          job_name?: string
          locked_until?: string
          token?: string
        }
        Relationships: []
      }
      automation_worker_heartbeats: {
        Row: {
          job_name: string
          last_failed_at: string | null
          last_started_at: string
          last_status: string
          last_succeeded_at: string | null
          updated_at: string
        }
        Insert: {
          job_name: string
          last_failed_at?: string | null
          last_started_at: string
          last_status: string
          last_succeeded_at?: string | null
          updated_at?: string
        }
        Update: {
          job_name?: string
          last_failed_at?: string | null
          last_started_at?: string
          last_status?: string
          last_succeeded_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      bowl_pool_championships: {
        Row: {
          championship_total_guess: number | null
          created_at: string
          final_total_difference: number | null
          id: string
          player_id: string
          season_id: string
          wins: number
        }
        Insert: {
          championship_total_guess?: number | null
          created_at?: string
          final_total_difference?: number | null
          id?: string
          player_id: string
          season_id: string
          wins: number
        }
        Update: {
          championship_total_guess?: number | null
          created_at?: string
          final_total_difference?: number | null
          id?: string
          player_id?: string
          season_id?: string
          wins?: number
        }
        Relationships: [
          {
            foreignKeyName: "bowl_pool_championships_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_championships_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      bowl_pool_entries: {
        Row: {
          championship_total_guess: number | null
          championship_total_submitted_at: string | null
          created_at: string
          id: string
          opted_in_at: string
          opted_out_at: string | null
          player_id: string
          preview_selections: Json
          season_id: string
          status: string
        }
        Insert: {
          championship_total_guess?: number | null
          championship_total_submitted_at?: string | null
          created_at?: string
          id?: string
          opted_in_at?: string
          opted_out_at?: string | null
          player_id: string
          preview_selections?: Json
          season_id: string
          status?: string
        }
        Update: {
          championship_total_guess?: number | null
          championship_total_submitted_at?: string | null
          created_at?: string
          id?: string
          opted_in_at?: string
          opted_out_at?: string | null
          player_id?: string
          preview_selections?: Json
          season_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "bowl_pool_entries_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_entries_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      bowl_pool_game_lines: {
        Row: {
          favorite_team_id: string | null
          game_id: string
          locked_at: string | null
          locked_spread: number
          manual_override: boolean
          source: string
          source_captured_at: string
          source_spread: number
        }
        Insert: {
          favorite_team_id?: string | null
          game_id: string
          locked_at?: string | null
          locked_spread: number
          manual_override?: boolean
          source: string
          source_captured_at: string
          source_spread: number
        }
        Update: {
          favorite_team_id?: string | null
          game_id?: string
          locked_at?: string | null
          locked_spread?: number
          manual_override?: boolean
          source?: string
          source_captured_at?: string
          source_spread?: number
        }
        Relationships: [
          {
            foreignKeyName: "bowl_pool_game_lines_favorite_team_id_fkey"
            columns: ["favorite_team_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_game_lines_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: true
            referencedRelation: "bowl_pool_games"
            referencedColumns: ["id"]
          },
        ]
      }
      bowl_pool_game_results: {
        Row: {
          entry_id: string
          game_id: string
          graded_at: string
          id: string
          reason: string
          result: string
        }
        Insert: {
          entry_id: string
          game_id: string
          graded_at?: string
          id?: string
          reason: string
          result: string
        }
        Update: {
          entry_id?: string
          game_id?: string
          graded_at?: string
          id?: string
          reason?: string
          result?: string
        }
        Relationships: [
          {
            foreignKeyName: "bowl_pool_game_results_entry_id_fkey"
            columns: ["entry_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_entries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_game_results_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_games"
            referencedColumns: ["id"]
          },
        ]
      }
      bowl_pool_games: {
        Row: {
          away_score: number | null
          away_team_id: string | null
          bowl_name: string
          created_at: string
          finalized_at: string | null
          home_score: number | null
          home_team_id: string | null
          id: string
          is_cfp: boolean
          kickoff_at: string
          line_lock_at: string
          odds_event_id: string | null
          order_index: number
          provider_game_id: string
          season_id: string
          status: string
          time_confirmed: boolean
          venue_city: string | null
          venue_name: string | null
          venue_state: string | null
        }
        Insert: {
          away_score?: number | null
          away_team_id?: string | null
          bowl_name: string
          created_at?: string
          finalized_at?: string | null
          home_score?: number | null
          home_team_id?: string | null
          id?: string
          is_cfp?: boolean
          kickoff_at: string
          line_lock_at: string
          odds_event_id?: string | null
          order_index: number
          provider_game_id: string
          season_id: string
          status?: string
          time_confirmed?: boolean
          venue_city?: string | null
          venue_name?: string | null
          venue_state?: string | null
        }
        Update: {
          away_score?: number | null
          away_team_id?: string | null
          bowl_name?: string
          created_at?: string
          finalized_at?: string | null
          home_score?: number | null
          home_team_id?: string | null
          id?: string
          is_cfp?: boolean
          kickoff_at?: string
          line_lock_at?: string
          odds_event_id?: string | null
          order_index?: number
          provider_game_id?: string
          season_id?: string
          status?: string
          time_confirmed?: boolean
          venue_city?: string | null
          venue_name?: string | null
          venue_state?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bowl_pool_games_away_team_id_fkey"
            columns: ["away_team_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_games_home_team_id_fkey"
            columns: ["home_team_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_games_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      bowl_pool_pick_history: {
        Row: {
          action: string
          actor_player_id: string | null
          created_at: string
          details: Json
          entry_id: string
          id: string
          pick_id: string | null
        }
        Insert: {
          action: string
          actor_player_id?: string | null
          created_at?: string
          details?: Json
          entry_id: string
          id?: string
          pick_id?: string | null
        }
        Update: {
          action?: string
          actor_player_id?: string | null
          created_at?: string
          details?: Json
          entry_id?: string
          id?: string
          pick_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bowl_pool_pick_history_actor_player_id_fkey"
            columns: ["actor_player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_pick_history_entry_id_fkey"
            columns: ["entry_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_entries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_pick_history_pick_id_fkey"
            columns: ["pick_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_picks"
            referencedColumns: ["id"]
          },
        ]
      }
      bowl_pool_picks: {
        Row: {
          entry_id: string
          game_id: string
          graded_at: string | null
          id: string
          result: string
          selected_team_id: string
          submitted_at: string
        }
        Insert: {
          entry_id: string
          game_id: string
          graded_at?: string | null
          id?: string
          result?: string
          selected_team_id: string
          submitted_at?: string
        }
        Update: {
          entry_id?: string
          game_id?: string
          graded_at?: string | null
          id?: string
          result?: string
          selected_team_id?: string
          submitted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "bowl_pool_picks_entry_id_fkey"
            columns: ["entry_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_entries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_picks_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_picks_selected_team_id_fkey"
            columns: ["selected_team_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_teams"
            referencedColumns: ["id"]
          },
        ]
      }
      bowl_pool_schedule_changes: {
        Row: {
          detected_at: string
          game_id: string
          id: string
          new_away_team_id: string | null
          new_home_team_id: string | null
          new_kickoff_at: string | null
          old_away_team_id: string | null
          old_home_team_id: string | null
          old_kickoff_at: string | null
          reviewed_at: string | null
        }
        Insert: {
          detected_at?: string
          game_id: string
          id?: string
          new_away_team_id?: string | null
          new_home_team_id?: string | null
          new_kickoff_at?: string | null
          old_away_team_id?: string | null
          old_home_team_id?: string | null
          old_kickoff_at?: string | null
          reviewed_at?: string | null
        }
        Update: {
          detected_at?: string
          game_id?: string
          id?: string
          new_away_team_id?: string | null
          new_home_team_id?: string | null
          new_kickoff_at?: string | null
          old_away_team_id?: string | null
          old_home_team_id?: string | null
          old_kickoff_at?: string | null
          reviewed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bowl_pool_schedule_changes_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_games"
            referencedColumns: ["id"]
          },
        ]
      }
      bowl_pool_seasons: {
        Row: {
          championship_game_id: string | null
          completed_at: string | null
          created_at: string
          first_kickoff_at: string | null
          id: string
          last_sync_dispatched_at: string | null
          player_visible_at: string
          season_year: number
          status: string
        }
        Insert: {
          championship_game_id?: string | null
          completed_at?: string | null
          created_at?: string
          first_kickoff_at?: string | null
          id?: string
          last_sync_dispatched_at?: string | null
          player_visible_at: string
          season_year: number
          status?: string
        }
        Update: {
          championship_game_id?: string | null
          completed_at?: string | null
          created_at?: string
          first_kickoff_at?: string | null
          id?: string
          last_sync_dispatched_at?: string | null
          player_visible_at?: string
          season_year?: number
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "bowl_pool_seasons_championship_game_id_fkey"
            columns: ["championship_game_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_games"
            referencedColumns: ["id"]
          },
        ]
      }
      bowl_pool_spread_history: {
        Row: {
          captured_at: string
          favorite_team_id: string | null
          game_id: string
          id: string
          pool_spread: number
          source: string
          source_spread: number
        }
        Insert: {
          captured_at?: string
          favorite_team_id?: string | null
          game_id: string
          id?: string
          pool_spread: number
          source: string
          source_spread: number
        }
        Update: {
          captured_at?: string
          favorite_team_id?: string | null
          game_id?: string
          id?: string
          pool_spread?: number
          source?: string
          source_spread?: number
        }
        Relationships: [
          {
            foreignKeyName: "bowl_pool_spread_history_favorite_team_id_fkey"
            columns: ["favorite_team_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bowl_pool_spread_history_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "bowl_pool_games"
            referencedColumns: ["id"]
          },
        ]
      }
      bowl_pool_teams: {
        Row: {
          abbreviation: string | null
          active: boolean
          conference_name: string | null
          created_at: string
          display_name: string
          id: string
          primary_color: string | null
          provider_team_id: string
          secondary_color: string | null
          short_name: string
        }
        Insert: {
          abbreviation?: string | null
          active?: boolean
          conference_name?: string | null
          created_at?: string
          display_name: string
          id?: string
          primary_color?: string | null
          provider_team_id: string
          secondary_color?: string | null
          short_name: string
        }
        Update: {
          abbreviation?: string | null
          active?: boolean
          conference_name?: string | null
          created_at?: string
          display_name?: string
          id?: string
          primary_color?: string | null
          provider_team_id?: string
          secondary_color?: string | null
          short_name?: string
        }
        Relationships: []
      }
      email_reminder_deliveries: {
        Row: {
          attempt_count: number
          attempted_at: string
          delivered_at: string | null
          email_address: string
          error_message: string | null
          id: string
          player_id: string
          provider_message_id: string | null
          provider_status: number | null
          reminder_id: string
          status: string
        }
        Insert: {
          attempt_count?: number
          attempted_at?: string
          delivered_at?: string | null
          email_address: string
          error_message?: string | null
          id?: string
          player_id: string
          provider_message_id?: string | null
          provider_status?: number | null
          reminder_id: string
          status?: string
        }
        Update: {
          attempt_count?: number
          attempted_at?: string
          delivered_at?: string | null
          email_address?: string
          error_message?: string | null
          id?: string
          player_id?: string
          provider_message_id?: string | null
          provider_status?: number | null
          reminder_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "email_reminder_deliveries_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "email_reminder_deliveries_reminder_id_fkey"
            columns: ["reminder_id"]
            isOneToOne: false
            referencedRelation: "push_reminders"
            referencedColumns: ["id"]
          },
        ]
      }
      game_lines: {
        Row: {
          favorite_team_id: string | null
          game_id: string
          locked_at: string
          locked_spread: number
          manual_override: boolean
          source: string
          source_captured_at: string
        }
        Insert: {
          favorite_team_id?: string | null
          game_id: string
          locked_at?: string
          locked_spread: number
          manual_override?: boolean
          source: string
          source_captured_at: string
        }
        Update: {
          favorite_team_id?: string | null
          game_id?: string
          locked_at?: string
          locked_spread?: number
          manual_override?: boolean
          source?: string
          source_captured_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "game_lines_favorite_team_id_fkey"
            columns: ["favorite_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "game_lines_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: true
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
        ]
      }
      games: {
        Row: {
          away_score: number | null
          away_team_id: string
          created_at: string
          external_game_id: string
          finalized_at: string | null
          game_note: string | null
          gameweek_key: string
          home_score: number | null
          home_team_id: string
          id: string
          is_international: boolean
          is_neutral_site: boolean
          kickoff_at: string
          line_lock_at: string
          odds_event_id: string | null
          schedule_source: string | null
          schedule_source_event_id: string | null
          scoring_period_id: string
          status: string
          venue_city: string | null
          venue_country: string | null
          venue_name: string | null
        }
        Insert: {
          away_score?: number | null
          away_team_id: string
          created_at?: string
          external_game_id: string
          finalized_at?: string | null
          game_note?: string | null
          gameweek_key: string
          home_score?: number | null
          home_team_id: string
          id?: string
          is_international?: boolean
          is_neutral_site?: boolean
          kickoff_at: string
          line_lock_at: string
          odds_event_id?: string | null
          schedule_source?: string | null
          schedule_source_event_id?: string | null
          scoring_period_id: string
          status?: string
          venue_city?: string | null
          venue_country?: string | null
          venue_name?: string | null
        }
        Update: {
          away_score?: number | null
          away_team_id?: string
          created_at?: string
          external_game_id?: string
          finalized_at?: string | null
          game_note?: string | null
          gameweek_key?: string
          home_score?: number | null
          home_team_id?: string
          id?: string
          is_international?: boolean
          is_neutral_site?: boolean
          kickoff_at?: string
          line_lock_at?: string
          odds_event_id?: string | null
          schedule_source?: string | null
          schedule_source_event_id?: string | null
          scoring_period_id?: string
          status?: string
          venue_city?: string | null
          venue_country?: string | null
          venue_name?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "games_away_team_id_fkey"
            columns: ["away_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "games_home_team_id_fkey"
            columns: ["home_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "games_scoring_period_id_fkey"
            columns: ["scoring_period_id"]
            isOneToOne: false
            referencedRelation: "scoring_periods"
            referencedColumns: ["id"]
          },
        ]
      }
      health_probe_states: {
        Row: {
          last_checked_at: string
          probe_name: string
          unhealthy_since: string | null
          updated_at: string
        }
        Insert: {
          last_checked_at?: string
          probe_name: string
          unhealthy_since?: string | null
          updated_at?: string
        }
        Update: {
          last_checked_at?: string
          probe_name?: string
          unhealthy_since?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      pick_history: {
        Row: {
          action: string
          actor_player_id: string | null
          created_at: string
          details: Json
          id: string
          pick_id: string
        }
        Insert: {
          action: string
          actor_player_id?: string | null
          created_at?: string
          details?: Json
          id?: string
          pick_id: string
        }
        Update: {
          action?: string
          actor_player_id?: string | null
          created_at?: string
          details?: Json
          id?: string
          pick_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pick_history_actor_player_id_fkey"
            columns: ["actor_player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_history_pick_id_fkey"
            columns: ["pick_id"]
            isOneToOne: false
            referencedRelation: "picks"
            referencedColumns: ["id"]
          },
        ]
      }
      pick_submission_receipts: {
        Row: {
          created_at: string
          player_id: string
          request_id: string
          scoring_period_id: string
        }
        Insert: {
          created_at?: string
          player_id: string
          request_id: string
          scoring_period_id: string
        }
        Update: {
          created_at?: string
          player_id?: string
          request_id?: string
          scoring_period_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pick_submission_receipts_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pick_submission_receipts_scoring_period_id_fkey"
            columns: ["scoring_period_id"]
            isOneToOne: false
            referencedRelation: "scoring_periods"
            referencedColumns: ["id"]
          },
        ]
      }
      picks: {
        Row: {
          game_id: string
          id: string
          locked_at: string | null
          player_id: string
          replaces_pick_id: string | null
          result: string
          scoring_period_id: string
          selected_team_id: string
          submitted_at: string
        }
        Insert: {
          game_id: string
          id?: string
          locked_at?: string | null
          player_id: string
          replaces_pick_id?: string | null
          result?: string
          scoring_period_id: string
          selected_team_id: string
          submitted_at?: string
        }
        Update: {
          game_id?: string
          id?: string
          locked_at?: string | null
          player_id?: string
          replaces_pick_id?: string | null
          result?: string
          scoring_period_id?: string
          selected_team_id?: string
          submitted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "picks_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_replaces_pick_id_fkey"
            columns: ["replaces_pick_id"]
            isOneToOne: false
            referencedRelation: "picks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_scoring_period_id_fkey"
            columns: ["scoring_period_id"]
            isOneToOne: false
            referencedRelation: "scoring_periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "picks_selected_team_id_fkey"
            columns: ["selected_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      pin_login_attempts: {
        Row: {
          attempted_at: string
          id: string
          pin_fingerprint: string
          source_fingerprint: string
        }
        Insert: {
          attempted_at?: string
          id?: string
          pin_fingerprint: string
          source_fingerprint: string
        }
        Update: {
          attempted_at?: string
          id?: string
          pin_fingerprint?: string
          source_fingerprint?: string
        }
        Relationships: []
      }
      pin_login_incidents: {
        Row: {
          alert_until: string
          attempted_pins: number
          detected_at: string
          id: string
          last_seen_at: string
          source_fingerprint: string
        }
        Insert: {
          alert_until: string
          attempted_pins: number
          detected_at?: string
          id?: string
          last_seen_at?: string
          source_fingerprint: string
        }
        Update: {
          alert_until?: string
          attempted_pins?: number
          detected_at?: string
          id?: string
          last_seen_at?: string
          source_fingerprint?: string
        }
        Relationships: []
      }
      players: {
        Row: {
          active: boolean
          auth_user_id: string | null
          created_at: string
          email_ats_due_enabled: boolean
          email_custom_enabled: boolean
          email_early_lock_enabled: boolean
          email_featured_window_reveal_enabled: boolean
          email_final_lines_enabled: boolean
          email_notifications_enabled: boolean
          email_pick_due_enabled: boolean
          email_pick_due_primetime_enabled: boolean
          email_pick_due_sunday_afternoon_enabled: boolean
          email_pick_due_sunday_early_enabled: boolean
          email_playoff_day_recap_enabled: boolean
          email_playoff_public_reveal_enabled: boolean
          email_sunday_early_reveal_enabled: boolean
          email_sunday_final_lines_enabled: boolean
          email_sunday_late_reveal_enabled: boolean
          email_survivor_due_enabled: boolean
          email_weekly_enabled: boolean
          email_weekly_recap_enabled: boolean
          first_name: string
          hide_pickem_eliminated_rows: boolean
          hide_survivor_eliminated_rows: boolean
          id: string
          is_commissioner: boolean
          last_active_at: string | null
          login_pin: string | null
          notification_email: string | null
          notification_preferences_updated_at: string | null
          push_ats_due_enabled: boolean
          push_custom_enabled: boolean
          push_early_lock_enabled: boolean
          push_final_lines_enabled: boolean
          push_pick_due_enabled: boolean
          push_survivor_due_enabled: boolean
          push_weekly_enabled: boolean
          push_weekly_recap_enabled: boolean
          show_bowl_card: boolean
          show_pool_action: boolean
          show_pool_chat: boolean
          show_survivor_standings: boolean
        }
        Insert: {
          active?: boolean
          auth_user_id?: string | null
          created_at?: string
          email_ats_due_enabled?: boolean
          email_custom_enabled?: boolean
          email_early_lock_enabled?: boolean
          email_featured_window_reveal_enabled?: boolean
          email_final_lines_enabled?: boolean
          email_notifications_enabled?: boolean
          email_pick_due_enabled?: boolean
          email_pick_due_primetime_enabled?: boolean
          email_pick_due_sunday_afternoon_enabled?: boolean
          email_pick_due_sunday_early_enabled?: boolean
          email_playoff_day_recap_enabled?: boolean
          email_playoff_public_reveal_enabled?: boolean
          email_sunday_early_reveal_enabled?: boolean
          email_sunday_final_lines_enabled?: boolean
          email_sunday_late_reveal_enabled?: boolean
          email_survivor_due_enabled?: boolean
          email_weekly_enabled?: boolean
          email_weekly_recap_enabled?: boolean
          first_name: string
          hide_pickem_eliminated_rows?: boolean
          hide_survivor_eliminated_rows?: boolean
          id?: string
          is_commissioner?: boolean
          last_active_at?: string | null
          login_pin?: string | null
          notification_email?: string | null
          notification_preferences_updated_at?: string | null
          push_ats_due_enabled?: boolean
          push_custom_enabled?: boolean
          push_early_lock_enabled?: boolean
          push_final_lines_enabled?: boolean
          push_pick_due_enabled?: boolean
          push_survivor_due_enabled?: boolean
          push_weekly_enabled?: boolean
          push_weekly_recap_enabled?: boolean
          show_bowl_card?: boolean
          show_pool_action?: boolean
          show_pool_chat?: boolean
          show_survivor_standings?: boolean
        }
        Update: {
          active?: boolean
          auth_user_id?: string | null
          created_at?: string
          email_ats_due_enabled?: boolean
          email_custom_enabled?: boolean
          email_early_lock_enabled?: boolean
          email_featured_window_reveal_enabled?: boolean
          email_final_lines_enabled?: boolean
          email_notifications_enabled?: boolean
          email_pick_due_enabled?: boolean
          email_pick_due_primetime_enabled?: boolean
          email_pick_due_sunday_afternoon_enabled?: boolean
          email_pick_due_sunday_early_enabled?: boolean
          email_playoff_day_recap_enabled?: boolean
          email_playoff_public_reveal_enabled?: boolean
          email_sunday_early_reveal_enabled?: boolean
          email_sunday_final_lines_enabled?: boolean
          email_sunday_late_reveal_enabled?: boolean
          email_survivor_due_enabled?: boolean
          email_weekly_enabled?: boolean
          email_weekly_recap_enabled?: boolean
          first_name?: string
          hide_pickem_eliminated_rows?: boolean
          hide_survivor_eliminated_rows?: boolean
          id?: string
          is_commissioner?: boolean
          last_active_at?: string | null
          login_pin?: string | null
          notification_email?: string | null
          notification_preferences_updated_at?: string | null
          push_ats_due_enabled?: boolean
          push_custom_enabled?: boolean
          push_early_lock_enabled?: boolean
          push_final_lines_enabled?: boolean
          push_pick_due_enabled?: boolean
          push_survivor_due_enabled?: boolean
          push_weekly_enabled?: boolean
          push_weekly_recap_enabled?: boolean
          show_bowl_card?: boolean
          show_pool_action?: boolean
          show_pool_chat?: boolean
          show_survivor_standings?: boolean
        }
        Relationships: []
      }
      playoff_day_eligibility: {
        Row: {
          evaluated_at: string
          game_day: string
          id: string
          is_eligible: boolean
          leader_wins_at_day_start: number
          player_id: string
          remaining_possible_wins: number
          scoring_period_id: string
          season_id: string
          wins_at_day_start: number
        }
        Insert: {
          evaluated_at?: string
          game_day: string
          id?: string
          is_eligible: boolean
          leader_wins_at_day_start: number
          player_id: string
          remaining_possible_wins: number
          scoring_period_id: string
          season_id: string
          wins_at_day_start: number
        }
        Update: {
          evaluated_at?: string
          game_day?: string
          id?: string
          is_eligible?: boolean
          leader_wins_at_day_start?: number
          player_id?: string
          remaining_possible_wins?: number
          scoring_period_id?: string
          season_id?: string
          wins_at_day_start?: number
        }
        Relationships: [
          {
            foreignKeyName: "playoff_day_eligibility_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "playoff_day_eligibility_scoring_period_id_fkey"
            columns: ["scoring_period_id"]
            isOneToOne: false
            referencedRelation: "scoring_periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "playoff_day_eligibility_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      pool_championships: {
        Row: {
          created_at: string
          crowned_at: string
          id: string
          player_id: string
          pool: string
          season_id: string | null
          season_year: number
        }
        Insert: {
          created_at?: string
          crowned_at?: string
          id?: string
          player_id: string
          pool: string
          season_id?: string | null
          season_year: number
        }
        Update: {
          created_at?: string
          crowned_at?: string
          id?: string
          player_id?: string
          pool?: string
          season_id?: string | null
          season_year?: number
        }
        Relationships: [
          {
            foreignKeyName: "pool_championships_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pool_championships_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      pool_chat_messages: {
        Row: {
          body: string
          championship_id: string | null
          created_at: string
          deleted_at: string | null
          deleted_by_player_id: string | null
          id: string
          is_moderator: boolean
          player_id: string
          season_id: string
        }
        Insert: {
          body: string
          championship_id?: string | null
          created_at?: string
          deleted_at?: string | null
          deleted_by_player_id?: string | null
          id?: string
          is_moderator?: boolean
          player_id: string
          season_id: string
        }
        Update: {
          body?: string
          championship_id?: string | null
          created_at?: string
          deleted_at?: string | null
          deleted_by_player_id?: string | null
          id?: string
          is_moderator?: boolean
          player_id?: string
          season_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pool_chat_messages_championship_id_fkey"
            columns: ["championship_id"]
            isOneToOne: true
            referencedRelation: "pool_championships"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pool_chat_messages_deleted_by_player_id_fkey"
            columns: ["deleted_by_player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pool_chat_messages_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pool_chat_messages_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      provider_failure_circuits: {
        Row: {
          consecutive_failures: number
          last_error: string
          last_failed_at: string
          next_retry_at: string
          provider_job: string
          updated_at: string
        }
        Insert: {
          consecutive_failures: number
          last_error: string
          last_failed_at: string
          next_retry_at: string
          provider_job: string
          updated_at?: string
        }
        Update: {
          consecutive_failures?: number
          last_error?: string
          last_failed_at?: string
          next_retry_at?: string
          provider_job?: string
          updated_at?: string
        }
        Relationships: []
      }
      push_reminder_deliveries: {
        Row: {
          attempted_at: string
          delivered_at: string | null
          error_message: string | null
          id: string
          player_id: string
          provider_status: number | null
          reminder_id: string
          status: string
          subscription_id: string
        }
        Insert: {
          attempted_at?: string
          delivered_at?: string | null
          error_message?: string | null
          id?: string
          player_id: string
          provider_status?: number | null
          reminder_id: string
          status?: string
          subscription_id: string
        }
        Update: {
          attempted_at?: string
          delivered_at?: string | null
          error_message?: string | null
          id?: string
          player_id?: string
          provider_status?: number | null
          reminder_id?: string
          status?: string
          subscription_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_reminder_deliveries_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "push_reminder_deliveries_reminder_id_fkey"
            columns: ["reminder_id"]
            isOneToOne: false
            referencedRelation: "push_reminders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "push_reminder_deliveries_subscription_id_fkey"
            columns: ["subscription_id"]
            isOneToOne: false
            referencedRelation: "push_subscriptions"
            referencedColumns: ["id"]
          },
        ]
      }
      push_reminders: {
        Row: {
          artwork_assets: Json
          audience: string
          automation_key: string | null
          body: string
          cancelled_at: string | null
          category: string
          created_at: string
          created_by_player_id: string
          id: string
          processing_started_at: string | null
          recap_snapshot: Json | null
          recap_snapshot_at: string | null
          scheduled_for: string
          sent_at: string | null
          source_game_ids: string[]
          source_scoring_period_id: string | null
          status: string
          suppression_reason: string | null
          title: string
          updated_at: string
        }
        Insert: {
          artwork_assets?: Json
          audience: string
          automation_key?: string | null
          body: string
          cancelled_at?: string | null
          category: string
          created_at?: string
          created_by_player_id: string
          id?: string
          processing_started_at?: string | null
          recap_snapshot?: Json | null
          recap_snapshot_at?: string | null
          scheduled_for: string
          sent_at?: string | null
          source_game_ids?: string[]
          source_scoring_period_id?: string | null
          status?: string
          suppression_reason?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          artwork_assets?: Json
          audience?: string
          automation_key?: string | null
          body?: string
          cancelled_at?: string | null
          category?: string
          created_at?: string
          created_by_player_id?: string
          id?: string
          processing_started_at?: string | null
          recap_snapshot?: Json | null
          recap_snapshot_at?: string | null
          scheduled_for?: string
          sent_at?: string | null
          source_game_ids?: string[]
          source_scoring_period_id?: string | null
          status?: string
          suppression_reason?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_reminders_created_by_player_id_fkey"
            columns: ["created_by_player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "push_reminders_source_scoring_period_id_fkey"
            columns: ["source_scoring_period_id"]
            isOneToOne: false
            referencedRelation: "scoring_periods"
            referencedColumns: ["id"]
          },
        ]
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          id: string
          p256dh: string
          player_id: string
          updated_at: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          id?: string
          p256dh: string
          player_id: string
          updated_at?: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          id?: string
          p256dh?: string
          player_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      reminder_templates: {
        Row: {
          body: string
          image_options: Json
          template_id: string
          title: string
          updated_at: string
          updated_by_player_id: string
        }
        Insert: {
          body: string
          image_options?: Json
          template_id: string
          title: string
          updated_at?: string
          updated_by_player_id: string
        }
        Update: {
          body?: string
          image_options?: Json
          template_id?: string
          title?: string
          updated_at?: string
          updated_by_player_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reminder_templates_updated_by_player_id_fkey"
            columns: ["updated_by_player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      schedule_change_reviews: {
        Row: {
          detected_at: string
          game_id: string
          id: string
          last_seen_at: string
          provider_snapshot: Json
          resolved_at: string | null
          review_type: string
          saved_snapshot: Json
        }
        Insert: {
          detected_at?: string
          game_id: string
          id?: string
          last_seen_at?: string
          provider_snapshot: Json
          resolved_at?: string | null
          review_type: string
          saved_snapshot: Json
        }
        Update: {
          detected_at?: string
          game_id?: string
          id?: string
          last_seen_at?: string
          provider_snapshot?: Json
          resolved_at?: string | null
          review_type?: string
          saved_snapshot?: Json
        }
        Relationships: [
          {
            foreignKeyName: "schedule_change_reviews_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
        ]
      }
      score_check_backoff: {
        Row: {
          attempts: number
          game_id: string
          last_checked_at: string
          next_check_at: string
          updated_at: string
        }
        Insert: {
          attempts?: number
          game_id: string
          last_checked_at?: string
          next_check_at?: string
          updated_at?: string
        }
        Update: {
          attempts?: number
          game_id?: string
          last_checked_at?: string
          next_check_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "score_check_backoff_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: true
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
        ]
      }
      scoring_periods: {
        Row: {
          created_at: string
          display_name: string
          display_order: number
          ends_at: string | null
          id: string
          max_picks: number
          period_type: string
          season_id: string
          starts_at: string | null
          status: string
        }
        Insert: {
          created_at?: string
          display_name: string
          display_order: number
          ends_at?: string | null
          id?: string
          max_picks: number
          period_type: string
          season_id: string
          starts_at?: string | null
          status?: string
        }
        Update: {
          created_at?: string
          display_name?: string
          display_order?: number
          ends_at?: string | null
          id?: string
          max_picks?: number
          period_type?: string
          season_id?: string
          starts_at?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "scoring_periods_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      season_turnover_runs: {
        Row: {
          blockers: Json
          completed_at: string | null
          deleted_counts: Json
          preserved_counts: Json
          previous_season_id: string | null
          started_at: string
          status: string
          target_season_id: string | null
          target_year: number
          updated_at: string
        }
        Insert: {
          blockers?: Json
          completed_at?: string | null
          deleted_counts?: Json
          preserved_counts?: Json
          previous_season_id?: string | null
          started_at?: string
          status: string
          target_season_id?: string | null
          target_year: number
          updated_at?: string
        }
        Update: {
          blockers?: Json
          completed_at?: string | null
          deleted_counts?: Json
          preserved_counts?: Json
          previous_season_id?: string | null
          started_at?: string
          status?: string
          target_season_id?: string | null
          target_year?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "season_turnover_runs_previous_season_id_fkey"
            columns: ["previous_season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "season_turnover_runs_target_season_id_fkey"
            columns: ["target_season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      seasons: {
        Row: {
          created_at: string
          id: string
          state: string
          survivor_champion_crowned_at: string | null
          survivor_champion_player_id: string | null
          year: number
        }
        Insert: {
          created_at?: string
          id?: string
          state?: string
          survivor_champion_crowned_at?: string | null
          survivor_champion_player_id?: string | null
          year: number
        }
        Update: {
          created_at?: string
          id?: string
          state?: string
          survivor_champion_crowned_at?: string | null
          survivor_champion_player_id?: string | null
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "seasons_survivor_champion_player_id_fkey"
            columns: ["survivor_champion_player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
        ]
      }
      spread_history: {
        Row: {
          captured_at: string
          favorite_team_id: string | null
          game_id: string
          id: string
          source: string
          spread: number
        }
        Insert: {
          captured_at?: string
          favorite_team_id?: string | null
          game_id: string
          id?: string
          source: string
          spread: number
        }
        Update: {
          captured_at?: string
          favorite_team_id?: string | null
          game_id?: string
          id?: string
          source?: string
          spread?: number
        }
        Relationships: [
          {
            foreignKeyName: "spread_history_favorite_team_id_fkey"
            columns: ["favorite_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "spread_history_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
        ]
      }
      survivor_entries: {
        Row: {
          eliminated_at: string | null
          eliminated_game_id: string | null
          eliminated_scoring_period_id: string | null
          entered_at: string
          id: string
          player_id: string
          season_id: string
          status: string
        }
        Insert: {
          eliminated_at?: string | null
          eliminated_game_id?: string | null
          eliminated_scoring_period_id?: string | null
          entered_at?: string
          id?: string
          player_id: string
          season_id: string
          status?: string
        }
        Update: {
          eliminated_at?: string | null
          eliminated_game_id?: string | null
          eliminated_scoring_period_id?: string | null
          entered_at?: string
          id?: string
          player_id?: string
          season_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "survivor_entries_eliminated_game_id_fkey"
            columns: ["eliminated_game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "survivor_entries_eliminated_scoring_period_id_fkey"
            columns: ["eliminated_scoring_period_id"]
            isOneToOne: false
            referencedRelation: "scoring_periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "survivor_entries_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "players"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "survivor_entries_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      survivor_picks: {
        Row: {
          game_id: string
          id: string
          locked_at: string | null
          result: string
          scoring_period_id: string
          selected_team_id: string
          submitted_at: string
          survivor_entry_id: string
        }
        Insert: {
          game_id: string
          id?: string
          locked_at?: string | null
          result?: string
          scoring_period_id: string
          selected_team_id: string
          submitted_at?: string
          survivor_entry_id: string
        }
        Update: {
          game_id?: string
          id?: string
          locked_at?: string | null
          result?: string
          scoring_period_id?: string
          selected_team_id?: string
          submitted_at?: string
          survivor_entry_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "survivor_picks_game_id_fkey"
            columns: ["game_id"]
            isOneToOne: false
            referencedRelation: "games"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "survivor_picks_scoring_period_id_fkey"
            columns: ["scoring_period_id"]
            isOneToOne: false
            referencedRelation: "scoring_periods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "survivor_picks_selected_team_id_fkey"
            columns: ["selected_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "survivor_picks_survivor_entry_id_fkey"
            columns: ["survivor_entry_id"]
            isOneToOne: false
            referencedRelation: "survivor_entries"
            referencedColumns: ["id"]
          },
        ]
      }
      sync_runs: {
        Row: {
          completed_at: string | null
          details: Json
          error_message: string | null
          id: string
          job_type: string
          provider: string
          started_at: string
          status: string
        }
        Insert: {
          completed_at?: string | null
          details?: Json
          error_message?: string | null
          id?: string
          job_type: string
          provider: string
          started_at?: string
          status: string
        }
        Update: {
          completed_at?: string | null
          details?: Json
          error_message?: string | null
          id?: string
          job_type?: string
          provider?: string
          started_at?: string
          status?: string
        }
        Relationships: []
      }
      teams: {
        Row: {
          abbreviation: string
          active: boolean
          city: string
          created_at: string
          full_name: string
          id: string
          mascot: string
        }
        Insert: {
          abbreviation: string
          active?: boolean
          city: string
          created_at?: string
          full_name: string
          id?: string
          mascot: string
        }
        Update: {
          abbreviation?: string
          active?: boolean
          city?: string
          created_at?: string
          full_name?: string
          id?: string
          mascot?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      activate_scoring_period_atomically: {
        Args: { activated_at?: string; target_scoring_period_id: string }
        Returns: {
          activated: boolean
          blocked_reason: string
        }[]
      }
      assert_scoring_period_accepts_picks: {
        Args: { evaluated_at?: string; target_scoring_period_id: string }
        Returns: undefined
      }
      automation_cron_secret_matches: {
        Args: { candidate_secret: string }
        Returns: boolean
      }
      automation_preflight: {
        Args: never
        Returns: {
          check_id: string
          detail: string
          label: string
          passed: boolean
        }[]
      }
      bowl_window_open: { Args: { evaluated_at?: string }; Returns: boolean }
      claim_automation_execution_lease: {
        Args: { lease_seconds?: number; target_job_name: string }
        Returns: string
      }
      claim_due_push_reminders: {
        Args: never
        Returns: {
          artwork_assets: Json
          audience: string
          automation_key: string | null
          body: string
          cancelled_at: string | null
          category: string
          created_at: string
          created_by_player_id: string
          id: string
          processing_started_at: string | null
          recap_snapshot: Json | null
          recap_snapshot_at: string | null
          scheduled_for: string
          sent_at: string | null
          source_game_ids: string[]
          source_scoring_period_id: string | null
          status: string
          suppression_reason: string | null
          title: string
          updated_at: string
        }[]
        SetofOptions: {
          from: "*"
          to: "push_reminders"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      clear_failed_pin_logins: {
        Args: { attempt_source_fingerprint: string }
        Returns: undefined
      }
      complete_scoring_period_atomically: {
        Args: {
          next_scoring_period_id: string
          rollover_at: string
          target_scoring_period_id: string
        }
        Returns: {
          activated_period_id: string
          completed_period_id: string
        }[]
      }
      correct_final_game_score_atomically: {
        Args: {
          actor_player_id?: string
          corrected_away_score: number
          corrected_home_score: number
          target_game_id: string
        }
        Returns: {
          ats_results_changed: number
          scoring_period_id: string
          survivor_results_changed: number
        }[]
      }
      dispatch_bowl_sync_if_due: { Args: never; Returns: boolean }
      dispatch_line_lock_if_due: { Args: never; Returns: boolean }
      dispatch_reminders_if_due: { Args: never; Returns: boolean }
      eliminate_survivor_no_picks: {
        Args: { evaluated_at?: string }
        Returns: {
          entries_eliminated: number
        }[]
      }
      ensure_annual_season_rollover: {
        Args: { evaluated_at?: string }
        Returns: {
          created: boolean
          season_id: string
          season_year: number
        }[]
      }
      ensure_regular_season_weeks: {
        Args: { target_season_id: string; week_count: number }
        Returns: number
      }
      ensure_survivor_entries: {
        Args: { target_season_id: string }
        Returns: undefined
      }
      finalize_games_atomically: {
        Args: { accepted_at?: string; final_games: Json }
        Returns: {
          ats_picks_graded: number
          final_scores_imported: number
          survivor_picks_graded: number
        }[]
      }
      grade_bowl_pool_final_picks: {
        Args: { evaluated_at?: string }
        Returns: number
      }
      import_full_schedule_atomically: {
        Args: {
          imported_at?: string
          period_assignments: Json
          schedule_games: Json
          target_season_id: string
        }
        Returns: {
          games_matched: number
          games_saved: number
          weeks_assigned: number
        }[]
      }
      import_schedule_atomically: {
        Args: {
          imported_at?: string
          period_assignments: Json
          preliminary_spreads: Json
          schedule_games: Json
          target_season_id: string
        }
        Returns: {
          games_saved: number
          new_weeks_assigned: number
          preliminary_spreads_saved: number
        }[]
      }
      line_lock_work_is_due: { Args: never; Returns: boolean }
      lock_official_lines_atomically: {
        Args: { decisions: Json; locked_at?: string }
        Returns: number
      }
      nfl_gameweek_key: { Args: { value: string }; Returns: string }
      normalize_bowl_pool_spread: {
        Args: { raw_spread: number }
        Returns: number
      }
      perform_annual_season_turnover: {
        Args: { evaluated_at?: string }
        Returns: Json
      }
      pin_login_cooldown_seconds: {
        Args: { attempt_source_fingerprint: string }
        Returns: number
      }
      project_database_usage_bytes: { Args: never; Returns: number }
      prune_operational_storage: {
        Args: { reference_time?: string }
        Returns: {
          deleted_count: number
          record_type: string
        }[]
      }
      purge_withdrawn_bowl_pool_drafts: {
        Args: { evaluated_at?: string }
        Returns: number
      }
      reconcile_full_schedule_atomically: {
        Args: {
          imported_at?: string
          schedule_games: Json
          target_season_id: string
        }
        Returns: {
          rescheduled_games: number
          review_games: number
        }[]
      }
      record_automation_worker_heartbeat: {
        Args: { target_job_name: string; target_status: string }
        Returns: undefined
      }
      record_bowl_game_disruption: {
        Args: {
          actor_player_id?: string
          disruption_status: string
          target_game_id: string
        }
        Returns: {
          picks_voided: number
        }[]
      }
      record_failed_pin_login: {
        Args: {
          attempt_pin_fingerprint: string
          attempt_source_fingerprint: string
          threshold?: number
          window_seconds?: number
        }
        Returns: {
          incident_id: string
          opened: boolean
        }[]
      }
      record_game_disruption: {
        Args: {
          actor_player_id?: string
          disruption_status: string
          target_game_id: string
        }
        Returns: {
          ats_voided: number
          survivor_voided: number
        }[]
      }
      recover_pending_ats_grades: {
        Args: never
        Returns: {
          picks_awaiting_line: number
          picks_graded: number
        }[]
      }
      refresh_bowl_pool_champion: {
        Args: { evaluated_at?: string; target_season_id: string }
        Returns: number
      }
      refresh_pickem_champion: {
        Args: { target_season_id: string }
        Returns: string
      }
      refresh_season_state_from_periods: {
        Args: { target_season_id: string }
        Returns: string
      }
      refresh_survivor_champion: {
        Args: { evaluated_at?: string; target_season_id: string }
        Returns: string
      }
      release_automation_execution_lease: {
        Args: { lease_token: string; target_job_name: string }
        Returns: boolean
      }
      reminder_delivery_is_due: { Args: never; Returns: boolean }
      replace_unlocked_picks: {
        Args: {
          replacement_picks: Json
          target_player_id: string
          target_scoring_period_id: string
        }
        Returns: undefined
      }
      replace_unlocked_picks_unchecked_20260826: {
        Args: {
          replacement_picks: Json
          target_player_id: string
          target_scoring_period_id: string
        }
        Returns: undefined
      }
      replace_unlocked_survivor_pick: {
        Args: {
          replacement_pick: Json
          target_scoring_period_id: string
          target_survivor_entry_id: string
        }
        Returns: undefined
      }
      replace_unlocked_survivor_pick_unchecked_20260826: {
        Args: {
          replacement_pick: Json
          target_scoring_period_id: string
          target_survivor_entry_id: string
        }
        Returns: undefined
      }
      reschedule_bowl_game: {
        Args: {
          actor_player_id: string
          new_kickoff_at: string
          target_game_id: string
        }
        Returns: {
          away_score: number | null
          away_team_id: string | null
          bowl_name: string
          created_at: string
          finalized_at: string | null
          home_score: number | null
          home_team_id: string | null
          id: string
          is_cfp: boolean
          kickoff_at: string
          line_lock_at: string
          odds_event_id: string | null
          order_index: number
          provider_game_id: string
          season_id: string
          status: string
          time_confirmed: boolean
          venue_city: string | null
          venue_name: string | null
          venue_state: string | null
        }
        SetofOptions: {
          from: "*"
          to: "bowl_pool_games"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      reschedule_game_atomically: {
        Args: {
          actor_player_id?: string
          revised_kickoff_at: string
          revised_line_lock_at: string
          target_game_id: string
        }
        Returns: {
          game_id: string
          line_reopened: boolean
          new_kickoff_at: string
          old_kickoff_at: string
        }[]
      }
      save_bowl_pool_submission: {
        Args: {
          evaluated_at?: string
          target_opted_in: boolean
          target_player_id: string
          target_season_id: string
          target_selections: Json
          target_tiebreaker: number
        }
        Returns: string
      }
      save_slate_selections:
        | {
            Args: {
              replacement_picks: Json
              replacement_survivor_pick: Json
              target_player_id: string
              target_scoring_period_id: string
              target_survivor_entry_id: string
            }
            Returns: undefined
          }
        | {
            Args: {
              replacement_picks: Json
              replacement_survivor_pick: Json
              request_id: string
              target_player_id: string
              target_scoring_period_id: string
              target_survivor_entry_id: string
            }
            Returns: undefined
          }
      season_phase: { Args: { evaluated_at?: string }; Returns: string }
      settle_bowl_pool_missing_picks: {
        Args: { evaluated_at?: string }
        Returns: number
      }
      settle_no_contest_picks: {
        Args: { evaluated_at?: string }
        Returns: {
          ats_losses: number
          survivor_losses: number
        }[]
      }
      snapshot_playoff_day_eligibility: {
        Args: { evaluated_at?: string; target_scoring_period_id: string }
        Returns: {
          picks_scratched: number
          players_eligible: number
          players_eliminated: number
          snapshot_day: string
        }[]
      }
      snapshot_playoff_day_eligibility_implementation: {
        Args: { evaluated_at?: string; target_scoring_period_id: string }
        Returns: {
          picks_scratched: number
          players_eligible: number
          players_eliminated: number
          snapshot_day: string
        }[]
      }
      snapshot_playoff_day_eligibility_unchecked_20260826: {
        Args: { evaluated_at?: string; target_scoring_period_id: string }
        Returns: {
          picks_scratched: number
          players_eligible: number
          players_eliminated: number
          snapshot_day: string
        }[]
      }
      storage_table_usage: {
        Args: never
        Returns: {
          estimated_rows: number
          index_bytes: number
          relation_name: string
          table_bytes: number
          total_bytes: number
        }[]
      }
      void_disrupted_picks: {
        Args: never
        Returns: {
          ats_voided: number
          survivor_voided: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
