"use client";
import { useEffect, useState } from "react";
import { fetchWithSession } from "@/lib/auth-session";
type Readiness = { checkedAt: string; seasonYear: number; playerVisibleAt: string; firstKickoffAt: string | null; games: number; missingTeams: number; missingLines: number; nextKickoffAt: string | null; openScheduleChanges: number; cronHealth: string; lockedGames: number; integrity: { healthy: boolean; problems: string[] }; settlement: { healthy: boolean; problems: string[] } };
export default function BowlPoolReadiness() {
  const [data, setData] = useState<Readiness | null>(null); const [error, setError] = useState("");
  useEffect(() => { void fetchWithSession("/api/admin/bowl-pool-readiness").then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setData(payload); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Readiness unavailable.")); }, []);
  return <section className="commissioner-tool" aria-labelledby="bowl-readiness-title"><p className="text-xs font-black tracking-[.16em] text-(color:--themed-text-28)">NCAA BOWL POOL</p><h2 className="mt-1 font-serif text-2xl font-bold" id="bowl-readiness-title">Bowl Pool readiness</h2>{error ? <p className="mt-2 text-sm text-red-700">{error}</p> : data ? <div className="mt-4 grid gap-2 sm:grid-cols-3"><p className="border border-zinc-300 bg-(color:--themed-bg-26) p-3 text-sm"><b>Schedule</b><br />{data.games} games · {data.missingTeams} missing team slots</p><p className="border border-zinc-300 bg-(color:--themed-bg-26) p-3 text-sm"><b>Lines</b><br />{data.missingLines} missing · {data.lockedGames} locked</p><p className={`border p-3 text-sm ${data.openScheduleChanges ? "border-(color:--themed-border-17) bg-(color:--themed-bg-21)" : "border-zinc-300 bg-(color:--themed-bg-26)"}`}><b>Schedule changes</b><br />{data.openScheduleChanges} awaiting review</p><p className="border border-zinc-300 bg-(color:--themed-bg-26) p-3 text-sm"><b>Next kickoff</b><br />{data.nextKickoffAt ? new Date(data.nextKickoffAt).toLocaleString("en-US", { timeZone: "America/New_York" }) : "None scheduled"}</p><p className={`border p-3 text-sm ${data.cronHealth === "healthy" ? "border-(color:--themed-border-20) bg-(color:--themed-bg-23)" : "border-(color:--themed-border-17) bg-(color:--themed-bg-21)"}`}><b>Cron health</b><br />{data.cronHealth}</p><p className={`border p-3 text-sm ${data.integrity.healthy ? "border-(color:--themed-border-20) bg-(color:--themed-bg-23)" : "border-(color:--themed-border-24) bg-(color:--themed-bg-24)"}`}><b>Schedule integrity</b><br />{data.integrity.healthy ? "No discrepancies" : data.integrity.problems.join(" ")}</p><p className={`border p-3 text-sm ${data.settlement.healthy ? "border-(color:--themed-border-20) bg-(color:--themed-bg-23)" : "border-(color:--themed-border-24) bg-(color:--themed-bg-24)"}`}><b>Settlement</b><br />{data.settlement.healthy ? "Grades and receipts reconcile" : data.settlement.problems.join(" ")}</p><p className="border border-zinc-300 bg-(color:--themed-bg-26) p-3 text-sm sm:col-span-3"><b>Launch gate</b><br />Player-visible {new Date(data.playerVisibleAt).toLocaleString("en-US", { timeZone: "America/New_York", timeZoneName: "short" })} · first kickoff {data.firstKickoffAt ? new Date(data.firstKickoffAt).toLocaleString("en-US", { timeZone: "America/New_York", timeZoneName: "short" }) : "not set"}</p></div> : <p className="mt-2 text-sm text-(color:--themed-text-28)">Checking schedule and worker health…</p>}</section>;
}
