"use client";
import { useState } from "react";
import ProviderChart from "@/components/provider-chart";
export type EfficiencyPoint = { slateStartedAt: string; creditsPerFinal: number | null; productiveRate: number | null; credits: number; finals: number; games: number; calls: number; attribution: string };
export type EfficiencySummary = { totalCredits: number; scoreCredits: number; spreadCredits: number; finalizedGames: number; creditsPerFinal: number | null; productiveRate: number | null; trend: string };
export type CreditUsage = { monthLabel: string; trackedCredits: number; forecastCredits: number; forecastTotal: number; forecastFrom: string | null; forecastAssumptions: string; reportedUsed: number | null; remaining: number | null; reportedAt: string | null; days: Array<{ date: string; credits: number; cumulative: number; scores: number; lines: number; other: number; estimatedCalls: number }>; calendarDays: Array<{ date: string; credits: number; cumulative: number; scores: number; lines: number; other: number; estimatedCalls: number; forecast: number; forecastCumulative: number | null; forecastScores: number; forecastLines: number; forecastOther: number; forecastGames: number; forecastSlates: number }> };
const date = (value: string, timeZone: string, time = false) => new Date(value).toLocaleString("en-US", { timeZone, month: "short", day: "numeric", ...(time ? { hour: "numeric", minute: "2-digit" } : {}) });
const format = (value: number | null) => value === null ? "-" : value.toLocaleString("en-US", { maximumFractionDigits: 1 });
const card = "min-w-0 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm sm:p-6";
const eyebrow = "text-[10px] font-bold uppercase tracking-[.18em] text-zinc-400";
export default function EfficiencyTrendPanel({ history, creditUsage, checkedAt, summary }: { history: EfficiencyPoint[]; creditUsage: CreditUsage; checkedAt: string; summary: EfficiencySummary }) {
  const [mode, setMode] = useState<"cumulative" | "daily">("cumulative"); const [range, setRange] = useState<"all" | "6">("all"); const observed = range === "6" ? history.slice(-6) : history; const todayKey = checkedAt.slice(0, 10);
  return <div className="mt-6 space-y-5"><section className={card} aria-label="Monthly provider credit usage"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className={eyebrow}>Provider spending · {creditUsage.monthLabel}</p><h3 className="mt-1 text-xl font-semibold tracking-tight text-zinc-900">Current-month credit usage</h3></div><div className="flex rounded-lg bg-zinc-100 p-1">{(["cumulative", "daily"] as const).map((value) => <button key={value} type="button" aria-pressed={mode === value} onClick={() => setMode(value)} className={`rounded-md px-3 py-1.5 text-xs font-semibold transition ${mode === value ? "bg-white text-zinc-900 shadow-sm" : "text-zinc-500 hover:text-zinc-900"}`}>{value === "cumulative" ? "Month to date" : "Daily spend"}</button>)}</div></div>
    <div className="my-5 grid grid-cols-2 gap-3 border-y border-zinc-100 py-4 sm:grid-cols-4">{[["Actual to date", creditUsage.trackedCredits], ["Forecast remaining", creditUsage.forecastCredits], ["Month-end forecast", creditUsage.forecastTotal], ["Provider reports used", creditUsage.reportedUsed]].map(([label, value]) => <div key={String(label)}><p className="text-[11px] text-zinc-500">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums tracking-tight sm:text-3xl">{format(value as number | null)}</p></div>)}</div>
    <ProviderChart key={mode} label="Current-month credit usage" points={creditUsage.calendarDays.map((day) => { const dayKey = day.date.slice(0, 10); const future = dayKey > todayKey; const today = dayKey === todayKey; return { label: `${date(day.date, "UTC")} · ${today ? "today so far" : future ? "forecast" : "daily close"} · UTC`, shortLabel: date(day.date, "UTC"), values: mode === "cumulative" ? { actual: future ? null : day.cumulative, forecast: future ? day.forecastCumulative : today && creditUsage.forecastFrom ? day.forecastCumulative : null } : { actual: future ? null : day.credits, forecast: future ? day.forecast : today && day.forecast > 0 ? day.forecast : null }, note: future || (today && day.forecast > 0) ? `${format(day.forecast)} forecast credits · ${day.forecastGames} scheduled games in ${day.forecastSlates} pooled slate${day.forecastSlates === 1 ? "" : "s"} · ${format(day.forecastScores)} score + ${format(day.forecastLines)} line checks` : `${day.credits} spent this day · Scores ${day.scores} · Line locks ${day.lines} · Other ${day.other}${day.estimatedCalls ? ` · ${day.estimatedCalls} estimated request costs` : ""}` }; })} series={[{ key: "actual", label: mode === "cumulative" ? "Actual credits" : "Actual daily spend", color: "#4f46e5", kind: mode === "cumulative" ? "area" : "bar" }, { key: "forecast", label: mode === "cumulative" ? "Forecast credits" : "Forecast daily spend", color: "#d97706", dash: mode === "cumulative" ? "6 5" : undefined, kind: mode === "cumulative" ? "area" : "bar" }]} />
    <p className="mt-4 text-[11px] leading-relaxed text-zinc-500">Month begins on the 1st, in UTC. Solid marks are recorded usage through today; amber marks are the projected remainder of the month. {creditUsage.forecastAssumptions}{creditUsage.reportedAt ? ` Quota last reported ${date(creditUsage.reportedAt, "America/New_York", true)} ET.` : ""}</p></section>
    <section className={card} aria-label="Slate efficiency"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><p className={eyebrow}>Score polling · Selected period</p><h3 className="mt-1 text-xl font-semibold tracking-tight text-zinc-900">Provider efficiency by game-time slate</h3><p className="mt-2 text-xs text-zinc-500">Each point is one kickoff slate · Eastern time</p></div><div className="flex rounded-lg bg-zinc-100 p-1">{(["all", "6"] as const).map((value) => <button key={value} type="button" aria-pressed={range === value} onClick={() => setRange(value)} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${range === value ? "bg-white text-zinc-900 shadow-sm" : "text-zinc-500"}`}>{value === "all" ? "All slates" : "Last 6"}</button>)}</div></div><div className="provider-efficiency-summary" aria-label="Provider efficiency summary"><div><span>Total credits</span><strong>{format(summary.totalCredits)}</strong><small>Score + spread checks</small></div><div><span>Score credits</span><strong>{format(summary.scoreCredits)}</strong><small>Final-score polling</small></div><div><span>Spread credits</span><strong>{format(summary.spreadCredits)}</strong><small>Lines and odds</small></div><div><span>Credits / final</span><strong>{format(summary.creditsPerFinal)}</strong><small>{summary.finalizedGames} finals imported</small></div><div><span>Productive checks</span><strong>{format(summary.productiveRate)}{summary.productiveRate === null ? "" : "%"}</strong><small>Checks that imported a final</small></div></div><ProviderChart key={range} label="Credits per final and productive checks by game-time slate" points={observed.map((point) => ({ label: `${date(point.slateStartedAt, "America/New_York", true)} ET · ${point.games} game${point.games === 1 ? "" : "s"}`, shortLabel: date(point.slateStartedAt, "America/New_York"), values: { credits: point.creditsPerFinal, productive: point.productiveRate }, note: point.attribution === "unavailable" ? "Overlapping slate activity - attribution unavailable" : point.attribution === "no-data" ? "No attributable polling records" : `${point.calls} checks · ${point.finals} fresh finals · Estimated attribution from polling times` }))} series={[{ key: "credits", label: "Credits / final", color: "#4f46e5" }, { key: "productive", label: "Productive checks", color: "#059669", axis: "right", suffix: "%" }]} /><p className="mt-4 text-[11px] leading-relaxed text-zinc-500">Lower credits per final and higher productive checks indicate better efficiency. Historical receipts lack slate IDs: non-overlapping polling windows are estimates; overlapping or missing data stays unplotted. No line bridges a missing value.</p></section></div>;
}
