"use client";

import { useEffect, useMemo, useState } from "react";
import { fetchWithSession } from "@/lib/auth-session";

type Point = { slateStartedAt: string; creditsPerFinal: number | null; productiveRate: number | null; credits: number; finals: number };
const WIDTH = 760, HEIGHT = 300, LEFT = 56, RIGHT = 56, TOP = 34, BOTTOM = 54;
const PLOT_WIDTH = WIDTH - LEFT - RIGHT, PLOT_HEIGHT = HEIGHT - TOP - BOTTOM;
function xFor(index: number, count: number) { return LEFT + (index / Math.max(1, count - 1)) * PLOT_WIDTH; }
function leftY(value: number, max: number) { return TOP + PLOT_HEIGHT - (value / max) * PLOT_HEIGHT; }
function rightY(value: number) { return TOP + PLOT_HEIGHT - (value / 100) * PLOT_HEIGHT; }
function formatSlate(value: string) { return new Date(value).toLocaleString("en-US", { timeZone: "America/New_York", weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit", timeZoneName: "short" }); }

export default function EfficiencyTrendPanel() {
  const [history, setHistory] = useState<Point[]>([]);
  useEffect(() => { let active = true; void fetchWithSession("/api/admin/grading-dashboard").then((response) => response.json()).then((payload) => { if (active && payload.metrics?.efficiency?.history) setHistory(payload.metrics.efficiency.history); }).catch(() => undefined); return () => { active = false; }; }, []);
  const observed = useMemo(() => history.filter((point) => point.credits > 0), [history]);
  if (!observed.length) return null;
  const creditMax = Math.max(1, Math.ceil(Math.max(...observed.map((point) => point.creditsPerFinal ?? 0)) / 10) * 10);
  const creditPoints = observed.flatMap((point, index) => point.creditsPerFinal === null ? [] : [{ x: xFor(index, observed.length), y: leftY(point.creditsPerFinal, creditMax) }]);
  const productivePoints = observed.flatMap((point, index) => point.productiveRate === null ? [] : [{ x: xFor(index, observed.length), y: rightY(point.productiveRate) }]);
  const ticks = [...new Set([0, Math.floor((observed.length - 1) / 2), observed.length - 1])];
  return <div className="mt-5 border border-zinc-300 bg-white p-4"><div className="flex flex-wrap items-baseline justify-between gap-3"><div><h3 className="font-serif text-xl font-bold">Provider efficiency by game-time slate</h3><p className="mt-1 text-sm text-zinc-600">Each point is one kickoff slate. Credit cost and productive-check rate use the score polls for that slate.</p></div><div className="flex gap-4 text-xs font-bold"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-indigo-700" />Credits / final</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-emerald-700" />Productive checks</span></div></div><div className="mt-4 overflow-x-auto"><svg aria-label="Credits per final and productive checks by game-time slate" className="h-auto min-w-[38rem] w-full" role="img" viewBox={`0 0 ${WIDTH} ${HEIGHT}`}><text x={LEFT} y="18" fill="#52525b" fontSize="12" fontWeight="700">Credits / final · lower is better</text><text x={WIDTH - RIGHT} y="18" fill="#52525b" fontSize="12" fontWeight="700" textAnchor="end">Productive checks · higher is better</text>{[0, 0.5, 1].map((fraction) => { const y = TOP + PLOT_HEIGHT - fraction * PLOT_HEIGHT; return <g key={fraction}><line x1={LEFT} x2={WIDTH - RIGHT} y1={y} y2={y} stroke="#e4e4e7" /><text x={LEFT - 8} y={y + 4} fill="#4338ca" fontSize="11" textAnchor="end">{Math.round(creditMax * fraction)}</text><text x={WIDTH - RIGHT + 8} y={y + 4} fill="#047857" fontSize="11">{Math.round(fraction * 100)}%</text></g>; })}{creditPoints.length > 1 ? <polyline fill="none" points={creditPoints.map((point) => `${point.x},${point.y}`).join(" ")} stroke="#4338ca" strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" /> : null}{productivePoints.length > 1 ? <polyline fill="none" points={productivePoints.map((point) => `${point.x},${point.y}`).join(" ")} stroke="#047857" strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" /> : null}{observed.map((point, index) => <g key={point.slateStartedAt}><title>{formatSlate(point.slateStartedAt)} · {point.creditsPerFinal ?? "—"} credits/final · {point.productiveRate ?? "—"}% productive · {point.credits} credits across {point.finals} final{point.finals === 1 ? "" : "s"}</title>{point.creditsPerFinal !== null ? <circle cx={xFor(index, observed.length)} cy={leftY(point.creditsPerFinal, creditMax)} r="4" fill="#4338ca" /> : null}{point.productiveRate !== null ? <circle cx={xFor(index, observed.length)} cy={rightY(point.productiveRate)} r="4" fill="#047857" /> : null}</g>)}{ticks.map((index) => <text key={index} x={xFor(index, observed.length)} y={HEIGHT - 20} fill="#71717a" fontSize="11" textAnchor={index === 0 ? "start" : index === observed.length - 1 ? "end" : "middle"}>{formatSlate(observed[index].slateStartedAt).replace(" EDT", "").replace(" EST", "")}</text>)}<text x={LEFT} y={HEIGHT - 4} fill="#71717a" fontSize="11">Game-time slate (Eastern time)</text></svg></div></div>;
}
