"use client";
import { useState } from "react";
import ProviderChart from "@/components/provider-chart";
import SlatePerformancePanel from "@/components/slate-performance-panel";
import type { LatencyMetric } from "@/components/latency-views-panel";
export type EfficiencyPoint = { slateStartedAt: string; creditsPerFinal: number | null; creditsPerGame: number | null; latencyMinutes: number | null; settledGames: number; productiveRate: number | null; credits: number; finals: number; games: number; calls: number; attribution: string };
export type EfficiencySummary = { totalCredits: number; scoreCredits: number; spreadCredits: number; finalizedGames: number; creditsPerFinal: number | null; productiveRate: number | null; trend: string };
export type CreditUsage = { monthLabel: string; trackedCredits: number; forecastCredits: number; forecastTotal: number; forecastFrom: string | null; forecastAssumptions: string; reportedUsed: number | null; providerLimit: number | null; untrackedCredits: number | null; sundayAverageCredits: number | null; regularSundaysElapsed?: number; remaining: number | null; reportedAt: string | null; days: Array<{ date: string; credits: number; cumulative: number; scores: number; lines: number; other: number; estimatedCalls: number }>; calendarDays: Array<{ date: string; credits: number; cumulative: number; scores: number; lines: number; other: number; estimatedCalls: number; forecast: number; forecastCumulative: number | null; forecastScores: number; forecastLines: number; forecastOther: number; forecastGames: number; forecastSlates: number }> };
const date = (value: string, timeZone: string, time = false) => new Date(value).toLocaleString("en-US", { timeZone, month: "short", day: "numeric", ...(time ? { hour: "numeric", minute: "2-digit" } : {}) });
const format = (value: number | null) => value === null ? "-" : value.toLocaleString("en-US", { maximumFractionDigits: 1 });
const card = "min-w-0 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm sm:p-6";
const eyebrow = "text-[10px] font-bold uppercase tracking-[.18em] text-zinc-400";
export default function EfficiencyTrendPanel({ history, creditUsage, checkedAt, summary, latencyMetric }: { history: EfficiencyPoint[]; creditUsage: CreditUsage; checkedAt: string; summary: EfficiencySummary; latencyMetric: LatencyMetric }) {
  const [mode, setMode] = useState<"cumulative" | "daily">("cumulative"); const todayKey = checkedAt.slice(0, 10);
  return <div className="mt-6 space-y-5"><section className={card} aria-label="Monthly provider credit usage"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className={eyebrow}>Provider spending · {creditUsage.monthLabel}</p><h3 className="mt-1 text-xl font-semibold tracking-tight text-zinc-900">Current-month credit usage</h3></div><div className="flex rounded-lg bg-zinc-100 p-1">{(["cumulative", "daily"] as const).map((value) => <button key={value} type="button" aria-pressed={mode === value} onClick={() => setMode(value)} className={`rounded-md px-3 py-1.5 text-xs font-semibold transition ${mode === value ? "bg-white text-zinc-900 shadow-sm" : "text-zinc-500 hover:text-zinc-900"}`}>{value === "cumulative" ? "Month to date" : "Daily spend"}</button>)}</div></div>
    <div className="my-5 grid grid-cols-2 gap-3 border-y border-zinc-100 py-4 lg:grid-cols-4">{[["Actual to date", creditUsage.trackedCredits], ["Not in app logs", creditUsage.untrackedCredits], ["Scheduled month-end forecast", creditUsage.forecastTotal], ["Regular-season Sunday average", creditUsage.sundayAverageCredits]].map(([label, value]) => <div key={String(label)}><p className="text-[11px] text-zinc-500">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums tracking-tight sm:text-3xl">{format(value as number | null)}</p>{label === "Regular-season Sunday average" ? <p className="mt-1 text-[10px] text-zinc-400">credits per elapsed Sunday{creditUsage.regularSundaysElapsed ? ` · ${creditUsage.regularSundaysElapsed} counted` : ""}</p> : label === "Scheduled month-end forecast" ? <p className="mt-1 text-[10px] text-zinc-400">{format(creditUsage.forecastCredits)} more expected</p> : null}</div>)}</div>
    <ProviderChart key={mode} label="Current-month credit usage" integerYAxis points={creditUsage.calendarDays.map((day) => { const dayKey = day.date.slice(0, 10); const future = dayKey > todayKey; const today = dayKey === todayKey; return { label: `${date(day.date, "UTC")} · ${today ? "today so far" : future ? "forecast" : "daily close"} · UTC`, shortLabel: date(day.date, "UTC"), values: (mode === "cumulative" ? { actual: future ? null : day.cumulative, forecast: future ? day.forecastCumulative : null } : { actualLines: future ? null : day.lines, actualScores: future ? null : day.scores, forecastLines: future ? day.forecastLines : null, forecastScores: future ? day.forecastScores : null }) as Record<string, number | null>, note: future ? `${format(day.forecast)} forecast credits · ${day.forecastGames} scheduled games in ${day.forecastSlates} pooled slate${day.forecastSlates === 1 ? "" : "s"}` : `${day.credits} spent this day` }; })} series={mode === "cumulative" ? [{ key: "actual", label: "Actual credits", color: "#4f46e5", kind: "area" }, { key: "forecast", label: "Forecast credits", color: "#d97706", dash: "6 5", kind: "area" }] : [{ key: "actualLines", label: "Actual line checks", color: "#5141c7", kind: "bar", stack: "actual" }, { key: "actualScores", label: "Actual score checks", color: "#a9a0f5", kind: "bar", stack: "actual" }, { key: "forecastLines", label: "Forecast line checks", color: "#b86b08", kind: "bar", stack: "forecast" }, { key: "forecastScores", label: "Forecast score checks", color: "#edc58d", kind: "bar", stack: "forecast" }]} />
    <p className="mt-4 text-[11px] leading-relaxed text-zinc-500">The chart shows activity recorded by this app, not the provider account total. “Not in app logs” reconciles the latest provider reading against those records. The month-end figure uses the schedule-based forecast shown in amber; there is no separate straight-line forecast. {creditUsage.forecastAssumptions}{creditUsage.reportedAt ? ` Provider balance last reported ${date(creditUsage.reportedAt, "America/New_York", true)} ET.` : ""}</p></section>
    <SlatePerformancePanel history={history} summary={summary} latencyMetric={latencyMetric} /></div>;
}
