"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { fetchWithSession, SessionUnavailableError } from "@/lib/auth-session";

type Dashboard = {
  checkedAt: string;
  status: "healthy" | "attention";
  periods: Array<{ id: string; displayName: string; status: string; type: string }>;
  period: { id: string; displayName: string; type: string; status: string } | null;
  metrics: { games: number; live: number; settled: number; awaitingGrade: number; attention: number; activePlayers: number; lastScoreSyncAt: string | null; lastScoreSyncAgeMinutes: number | null; latestScoreSyncStatus: string; providerAllowance: number | null; pickOutcomes: { win: number; loss: number; void: number; pending: number }; survivorEntries: { active: number; eliminated: number; complete: number }; reminders: { scheduled: number; sending: number; sent: number; cancelled: number; test: number }; efficiency: { totalCredits: number; finalizedGames: number; creditsPerFinal: number | null; productiveRate: number | null; trend: string }; settlementLatency: { averageMinutes: number | null; slowestMinutes: number | null; samples: number }; comparison: { previousPeriod: string | null; previousAverageMinutes: number | null; deltaMinutes: number | null }; readiness: { scheduleLoaded: boolean; linesLocked: number; lineTotal: number; nextKickoffAt: string | null; nextLineLockAt: string | null } } | null;
  games: Array<{ id: string; away: string; home: string; awayName: string; homeName: string; kickoffAt: string; finalizedAt: string | null; status: string; state: string; score: string | null; needsAttention: boolean; picks: { total: number; pending: number; graded: number }; survivor: { total: number; pending: number } }>;
  attention: Array<{ id: string; severity: string; title: string; detail: string }>;
  audit: Array<{ id: string; action: string; entityType: string; details: Record<string, unknown>; createdAt: string }>;
  workerRuns: Array<{ jobType: string; status: string; startedAt: string; completedAt: string | null; error: string | null }>;
  incidents: Array<{ id: string; title: string; severity: string; detectedAt: string; lastSeenAt: string; resolvedAt: string | null }>;
  reminders: Array<{ id: string; category: string; title: string; scheduledFor: string; status: string }>;
  polling: { recommendedPlan: string; plans: Array<{ id: string; label: string; checksPerGame: number; expectedMinutesAfterFinal: number; description: string; weeklyCredits: number; monthlyCredits: number; periodCredits: number; versusObservedWeeklyCredits: number | null }>; assumptions: { approvalRequired: boolean; appliesAutomatically: boolean } };
};

const stateLabels: Record<string, string> = { scheduled: "Scheduled", live: "Live", settled: "Settled", needs_review: "Needs review", stale: "Stale", held: "Held" };

function local(value: string | null) { return value ? new Date(value).toLocaleString("en-US", { timeZone: "America/New_York", hour: "numeric", minute: "2-digit", timeZoneName: "short" }) : "—"; }

export default function GradingDashboard() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [filter, setFilter] = useState<"all" | "attention" | "live" | "settled">("all");
  const [periodId, setPeriodId] = useState("");
  const [selectedGameId, setSelectedGameId] = useState("");
  const [copied, setCopied] = useState(false);

  const refresh = useCallback(async (selectedPeriodId = periodId) => {
    setLoading(true); setError("");
    try {
      const response = await fetchWithSession(selectedPeriodId ? `/api/admin/grading-dashboard?periodId=${encodeURIComponent(selectedPeriodId)}` : "/api/admin/grading-dashboard");
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error ?? "The grading dashboard could not load.");
      setData(payload);
      setPeriodId(payload.period?.id ?? "");
      setSelectedGameId((current) => current && payload.games.some((game: Dashboard["games"][number]) => game.id === current) ? current : payload.games.find((game: Dashboard["games"][number]) => game.needsAttention)?.id ?? payload.games[0]?.id ?? "");
    } catch (reason) {
      if (reason instanceof SessionUnavailableError) window.location.replace("/login");
      else setError(reason instanceof Error ? reason.message : "The grading dashboard could not load.");
    } finally { setLoading(false); }
  }, [periodId]);
  useEffect(() => { const initial = window.setTimeout(() => void refresh(), 0); const timer = window.setInterval(() => void refresh(), 60000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [refresh]);

  const filteredGames = useMemo(() => data?.games.filter((game) => filter === "all" || (filter === "attention" ? game.needsAttention : filter === game.state)) ?? [], [data, filter]);
  const metric = data?.metrics;
  const selectedGame = data?.games.find((game) => game.id === selectedGameId) ?? null;
  async function copySnapshot() {
    if (!data || !metric) return;
    const snapshot = [`Pick'em grading snapshot · ${data.period?.displayName ?? "No period"}`, `Status: ${data.status}`, `Games: ${metric.games} · live ${metric.live} · settled ${metric.settled}`, `Pending grades: ${metric.awaitingGrade} · attention: ${metric.attention}`, `Last score sync: ${local(metric.lastScoreSyncAt)}`, `Credits/final: ${metric.efficiency.creditsPerFinal ?? "—"}`, `Checked: ${local(data.checkedAt)}`].join("\n");
    try { await navigator.clipboard.writeText(snapshot); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); }
  }
  return <section className="border-b-2 border-zinc-900 py-8" aria-labelledby="grading-dashboard-title">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black tracking-[.16em] text-zinc-600">GRADING CONTROL CENTER</p><h2 className="mt-1 font-serif text-3xl font-bold" id="grading-dashboard-title">Live grading dashboard</h2><p className="mt-2 max-w-3xl text-zinc-700">See what has settled, what is moving, and exactly where the next manual decision is needed.</p></div><div className="flex flex-wrap items-center gap-2"><label className="text-xs font-black tracking-wide text-zinc-600" htmlFor="grading-period">PERIOD</label><select className="border border-zinc-900 bg-white px-3 py-2 text-sm font-semibold" id="grading-period" onChange={(event) => { setPeriodId(event.target.value); void refresh(event.target.value); }} value={periodId}>{data?.periods.map((item) => <option key={item.id} value={item.id}>{item.displayName} · {item.status}</option>)}</select><button className="border border-zinc-900 bg-white px-3 py-2 text-sm font-bold disabled:opacity-40" disabled={!data} onClick={() => void copySnapshot()} type="button">{copied ? "Copied" : "Copy snapshot"}</button><button className="border border-zinc-900 bg-white px-4 py-2 text-sm font-bold disabled:opacity-40" disabled={loading} onClick={() => void refresh()} type="button">{loading ? "Checking…" : "Refresh dashboard"}</button></div></div>
    {error ? <p className="mt-5 border-l-4 border-red-700 bg-red-50 p-4 font-semibold text-red-900">{error}</p> : null}
    {data?.period && metric ? <>
      <div className={`mt-6 border p-4 ${data.status === "attention" ? "border-red-700 bg-red-50" : "border-green-800 bg-green-50"}`}><p className="text-xs font-black tracking-[.14em]">{data.status === "attention" ? "ACTION NEEDED" : "RUNNING NORMALLY"}</p><p className="mt-1 font-serif text-2xl font-bold">{data.period.displayName} · {metric.live ? `${metric.live} live` : `${metric.settled} settled`}</p><p className="mt-1 text-sm">{data.attention.length ? `${data.attention.length} item${data.attention.length === 1 ? "" : "s"} need review before the pipeline is fully clear.` : "No grading exceptions are open."}</p></div>
      <div className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{[["GAMES", metric.games], ["LIVE", metric.live], ["SETTLED", metric.settled], ["PENDING GRADES", metric.awaitingGrade], ["ATTENTION", metric.attention], ["ACTIVE PLAYERS", metric.activePlayers]].map(([label, value]) => <div className="border border-zinc-300 bg-white p-3" key={label as string}><p className="text-[11px] font-black tracking-[.14em] text-zinc-500">{label}</p><p className="mt-1 font-serif text-2xl font-bold tabular-nums">{value}</p></div>)}</div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
        <div className="border border-zinc-300 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-300 p-4"><div><h3 className="font-serif text-xl font-bold">Game pipeline</h3><p className="mt-1 text-sm text-zinc-600">Score sync: {metric.latestScoreSyncStatus} · {metric.lastScoreSyncAgeMinutes === null ? "no successful run" : `${metric.lastScoreSyncAgeMinutes}m ago`}</p></div><div className="flex gap-1 text-xs font-bold"><button className={`border px-2 py-1 ${filter === "all" ? "bg-zinc-900 text-white" : ""}`} onClick={() => setFilter("all")} type="button">All</button><button className={`border px-2 py-1 ${filter === "attention" ? "bg-zinc-900 text-white" : ""}`} onClick={() => setFilter("attention")} type="button">Attention</button><button className={`border px-2 py-1 ${filter === "live" ? "bg-zinc-900 text-white" : ""}`} onClick={() => setFilter("live")} type="button">Live</button></div></div><div className="divide-y divide-zinc-200">{filteredGames.length ? filteredGames.map((game) => <div className="grid gap-2 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center" key={game.id}><div><p className="font-bold">{game.away} at {game.home} <span className="ml-2 text-xs font-black uppercase tracking-wide text-zinc-500">{stateLabels[game.state] ?? game.state}</span></p><p className="mt-1 text-xs text-zinc-600">{local(game.kickoffAt)} · {game.score ?? "No final score"} · {game.picks.graded}/{game.picks.total} Pick’em grades</p></div><p className="text-sm font-bold tabular-nums">{game.survivor.total ? `${game.survivor.total - game.survivor.pending}/${game.survivor.total} Survivor` : "No Survivor picks"}</p><span className={`justify-self-start border px-2 py-1 text-xs font-black uppercase tracking-wide sm:justify-self-end ${game.needsAttention ? "border-red-700 bg-red-50 text-red-800" : game.state === "live" ? "border-amber-700 bg-amber-50 text-amber-900" : "border-zinc-300 text-zinc-600"}`}>{game.needsAttention ? "Review" : stateLabels[game.state] ?? game.state}</span></div>) : <p className="p-5 text-sm text-zinc-600">No games match this view.</p>}</div></div>
        <div className="space-y-5"><div className="border border-zinc-300 bg-white p-4"><h3 className="font-serif text-xl font-bold">Attention queue</h3>{data.attention.length ? <div className="mt-3 space-y-3">{data.attention.slice(0, 6).map((item) => <div className="border-l-4 border-red-700 bg-red-50 p-3" key={item.id}><p className="font-bold">{item.title}</p><p className="mt-1 text-sm">{item.detail}</p></div>)}</div> : <p className="mt-3 text-sm text-zinc-700">Nothing needs intervention right now.</p>}</div><div className="border border-zinc-300 bg-white p-4"><h3 className="font-serif text-xl font-bold">Next operational signals</h3><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between gap-3"><dt className="text-zinc-600">Last score sync</dt><dd className="font-semibold">{local(metric.lastScoreSyncAt)}</dd></div><div className="flex justify-between gap-3"><dt className="text-zinc-600">Next scheduled message</dt><dd className="max-w-[12rem] text-right font-semibold">{(() => { const next = data.reminders.find((reminder) => reminder.status === "scheduled"); return next ? `${next.title} · ${local(next.scheduledFor)}` : "None scheduled"; })()}</dd></div><div className="flex justify-between gap-3"><dt className="text-zinc-600">Provider allowance</dt><dd className="font-semibold">{metric.providerAllowance ?? "Not reported"}</dd></div><div className="flex justify-between gap-3"><dt className="text-zinc-600">Dashboard checked</dt><dd className="font-semibold">{local(data.checkedAt)}</dd></div></dl></div></div>
      </div>
      <div className="mt-5 grid gap-5 md:grid-cols-2"><div className="border border-zinc-300 bg-white p-4"><h3 className="font-serif text-xl font-bold">Participant impact</h3><p className="mt-1 text-sm text-zinc-600">What the current grading state means for the pool.</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">PICK’EM RESULTS</p><p className="mt-1 font-semibold">{metric.pickOutcomes.win} wins · {metric.pickOutcomes.loss} losses</p><p className="mt-1 text-xs text-zinc-600">{metric.pickOutcomes.pending} pending · {metric.pickOutcomes.void} void</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">SURVIVOR</p><p className="mt-1 font-semibold">{metric.survivorEntries.active} active</p><p className="mt-1 text-xs text-zinc-600">{metric.survivorEntries.eliminated} eliminated · {metric.survivorEntries.complete} complete</p></div></div></div><div className="border border-zinc-300 bg-white p-4"><h3 className="font-serif text-xl font-bold">Notification readiness</h3><p className="mt-1 text-sm text-zinc-600">The delivery queue visible from the grading view.</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className={`border p-3 ${metric.reminders.scheduled || metric.reminders.sending ? "border-amber-700 bg-amber-50" : "border-zinc-200"}`}><p className="text-xs font-black tracking-wide text-zinc-500">QUEUED</p><p className="mt-1 font-semibold">{metric.reminders.scheduled} scheduled</p><p className="mt-1 text-xs text-zinc-600">{metric.reminders.sending} sending</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">DELIVERY HISTORY</p><p className="mt-1 font-semibold">{metric.reminders.sent} sent</p><p className="mt-1 text-xs text-zinc-600">{metric.reminders.cancelled} cancelled · {metric.reminders.test} test</p></div></div></div></div>
      <div className="mt-5 border border-zinc-300 bg-white p-4"><h3 className="font-serif text-xl font-bold">Release readiness</h3><p className="mt-1 text-sm text-zinc-600">The next operational milestones for this scoring period.</p><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div className={`border p-3 ${metric.readiness.scheduleLoaded ? "border-green-700 bg-green-50" : "border-red-700 bg-red-50"}`}><p className="text-xs font-black tracking-wide text-zinc-500">SCHEDULE</p><p className="mt-1 font-semibold">{metric.readiness.scheduleLoaded ? `${metric.games} games loaded` : "No games loaded"}</p></div><div className={`border p-3 ${metric.readiness.linesLocked === metric.readiness.lineTotal ? "border-green-700 bg-green-50" : "border-amber-700 bg-amber-50"}`}><p className="text-xs font-black tracking-wide text-zinc-500">OFFICIAL LINES</p><p className="mt-1 font-semibold">{metric.readiness.linesLocked}/{metric.readiness.lineTotal} locked</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">NEXT KICKOFF</p><p className="mt-1 font-semibold">{local(metric.readiness.nextKickoffAt)}</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">NEXT LINE LOCK</p><p className="mt-1 font-semibold">{local(metric.readiness.nextLineLockAt)}</p></div></div></div>
      <div className="mt-5 border border-zinc-300 bg-white p-4"><h3 className="font-serif text-xl font-bold">Provider efficiency</h3><p className="mt-1 text-sm text-zinc-600">A 30-day view of the score-provider work behind this dashboard.</p><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">CREDITS TRACKED</p><p className="mt-1 font-semibold">{metric.efficiency.totalCredits}</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">CREDITS / FINAL</p><p className="mt-1 font-semibold">{metric.efficiency.creditsPerFinal ?? "—"}</p><p className="mt-1 text-xs text-zinc-600">{metric.efficiency.finalizedGames} finals imported</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">PRODUCTIVE CHECKS</p><p className="mt-1 font-semibold">{metric.efficiency.productiveRate === null ? "—" : `${metric.efficiency.productiveRate}%`}</p><p className="mt-1 text-xs text-zinc-600">Checks that imported a final</p></div><div className={`border p-3 ${metric.efficiency.trend === "worsening" ? "border-amber-700 bg-amber-50" : "border-green-700 bg-green-50"}`}><p className="text-xs font-black tracking-wide text-zinc-500">7-DAY TREND</p><p className="mt-1 font-semibold capitalize">{metric.efficiency.trend}</p></div></div></div>
      <div className="mt-5 grid gap-5 md:grid-cols-2"><div className="border border-zinc-300 bg-white p-4"><h3 className="font-serif text-xl font-bold">Settlement latency</h3><p className="mt-1 text-sm text-zinc-600">Time from kickoff to an accepted final for this period.</p><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">AVERAGE</p><p className="mt-1 font-semibold">{metric.settlementLatency.averageMinutes === null ? "—" : `${metric.settlementLatency.averageMinutes}m`}</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">SLOWEST</p><p className="mt-1 font-semibold">{metric.settlementLatency.slowestMinutes === null ? "—" : `${metric.settlementLatency.slowestMinutes}m`}</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">SAMPLES</p><p className="mt-1 font-semibold">{metric.settlementLatency.samples}</p></div></div></div><div className="border border-zinc-300 bg-white p-4"><h3 className="font-serif text-xl font-bold">Period comparison</h3><p className="mt-1 text-sm text-zinc-600">Settlement speed versus {metric.comparison.previousPeriod ?? "the previous period"}.</p><p className="mt-4 font-serif text-2xl font-bold">{metric.comparison.deltaMinutes === null ? "—" : `${metric.comparison.deltaMinutes > 0 ? "+" : ""}${metric.comparison.deltaMinutes}m`}</p><p className="mt-1 text-sm">{metric.comparison.deltaMinutes === null ? "Not enough settled history to compare." : metric.comparison.deltaMinutes > 0 ? "Slower than the previous period." : metric.comparison.deltaMinutes < 0 ? "Faster than the previous period." : "The same average settlement time."}</p></div></div>
      <div className="mt-5 border border-zinc-300 bg-white p-4"><div className="flex flex-wrap items-baseline justify-between gap-3"><div><h3 className="font-serif text-xl font-bold">Worker activity</h3><p className="mt-1 text-sm text-zinc-600">The latest score and line-lock invocations.</p></div><span className="text-xs font-bold text-zinc-500">Auto-refreshes with the dashboard</span></div>{data.workerRuns.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[34rem] text-left text-sm"><thead className="border-b border-zinc-300 text-xs uppercase tracking-wide text-zinc-500"><tr><th className="pb-2 pr-3">Worker</th><th className="pb-2 pr-3">Status</th><th className="pb-2 pr-3">Started</th><th className="pb-2">Completed</th></tr></thead><tbody>{data.workerRuns.map((run, index) => <tr className="border-b border-zinc-100" key={`${run.jobType}-${run.startedAt}-${index}`}><td className="py-2 pr-3 font-semibold">{run.jobType.replaceAll("_", " ")}</td><td className={`py-2 pr-3 font-bold ${run.status === "success" ? "text-green-800" : run.status === "failed" ? "text-red-800" : "text-amber-800"}`}>{run.status}</td><td className="py-2 pr-3 text-xs text-zinc-600">{local(run.startedAt)}</td><td className="py-2 text-xs text-zinc-600">{run.completedAt ? local(run.completedAt) : run.error ?? "Still running"}</td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-zinc-600">No score or line-lock worker runs have been recorded.</p>}</div>
      <div className="mt-5 border border-zinc-300 bg-white p-4"><div className="flex flex-wrap items-baseline justify-between gap-3"><div><h3 className="font-serif text-xl font-bold">Recent operational history</h3><p className="mt-1 text-sm text-zinc-600">The latest durable events behind the live numbers.</p></div><span className="text-xs font-bold text-zinc-500">{data.audit.length} recent events</span></div>{data.audit.length ? <ol className="mt-4 divide-y divide-zinc-200">{data.audit.slice(0, 8).map((entry) => <li className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1 py-3 text-sm" key={entry.id}><span><strong>{entry.action.replaceAll("_", " ")}</strong><span className="ml-2 text-zinc-500">{entry.entityType}</span></span><time className="text-xs text-zinc-500" dateTime={entry.createdAt}>{local(entry.createdAt)}</time></li>)}</ol> : <p className="mt-4 text-sm text-zinc-600">No recent grading events have been recorded.</p>}</div>
      <div className="mt-5 border border-zinc-300 bg-white p-4"><div className="flex flex-wrap items-baseline justify-between gap-3"><div><h3 className="font-serif text-xl font-bold">Incident posture</h3><p className="mt-1 text-sm text-zinc-600">Open and recently resolved watchdog incidents.</p></div><span className="text-xs font-bold text-zinc-500">{data.incidents.filter((incident) => !incident.resolvedAt).length} open</span></div>{data.incidents.length ? <div className="mt-4 grid gap-2 sm:grid-cols-2">{data.incidents.slice(0, 6).map((incident) => <div className={`border p-3 ${incident.resolvedAt ? "border-zinc-200 bg-zinc-50" : "border-red-700 bg-red-50"}`} key={incident.id}><div className="flex items-center justify-between gap-3"><p className="font-bold">{incident.title}</p><span className="text-xs font-black uppercase tracking-wide">{incident.resolvedAt ? "Resolved" : incident.severity}</span></div><p className="mt-1 text-xs text-zinc-600">Detected {local(incident.detectedAt)} · {incident.resolvedAt ? `cleared ${local(incident.resolvedAt)}` : `last seen ${local(incident.lastSeenAt)}`}</p></div>)}</div> : <p className="mt-4 text-sm text-zinc-600">No watchdog incidents have been recorded recently.</p>}</div>
      {selectedGame ? <div className="mt-5 border border-zinc-300 bg-white p-4"><div className="flex flex-wrap items-baseline justify-between gap-3"><div><p className="text-xs font-black tracking-[.14em] text-zinc-500">GAME INSPECTOR</p><h3 className="mt-1 font-serif text-xl font-bold">{selectedGame.awayName} at {selectedGame.homeName}</h3></div><select aria-label="Inspect game" className="border border-zinc-900 bg-white px-3 py-2 text-sm font-semibold" onChange={(event) => setSelectedGameId(event.target.value)} value={selectedGame.id}>{data.games.map((game) => <option key={game.id} value={game.id}>{game.away} at {game.home}</option>)}</select></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">STATE</p><p className="mt-1 font-semibold">{stateLabels[selectedGame.state] ?? selectedGame.state}</p><p className="mt-1 text-xs text-zinc-600">Kickoff {local(selectedGame.kickoffAt)}</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">SCORE</p><p className="mt-1 font-semibold">{selectedGame.score ?? "Not final"}</p><p className="mt-1 text-xs text-zinc-600">Finalized {local(selectedGame.finalizedAt)}</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">PICK’EM</p><p className="mt-1 font-semibold">{selectedGame.picks.graded}/{selectedGame.picks.total} graded</p><p className="mt-1 text-xs text-zinc-600">{selectedGame.picks.pending} pending</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">SURVIVOR</p><p className="mt-1 font-semibold">{selectedGame.survivor.total - selectedGame.survivor.pending}/{selectedGame.survivor.total} graded</p><p className="mt-1 text-xs text-zinc-600">{selectedGame.survivor.pending} pending</p></div></div></div> : null}
    </> : loading ? <div className="mt-6 h-48 animate-pulse bg-zinc-200" aria-label="Loading grading dashboard" /> : null}
  </section>;
}
