"use client";

import { useEffect, useState } from "react";
import { fetchWithSession } from "@/lib/auth-session";

type Plan = { id: string; label: string; checksPerGame: number; description: string; monthlyCredits: number; periodCredits: number };
type Poll = { startedAt: string; completedAt: string | null; pollingMode: string; eligibleGames: number; completedGamesFound: number; finalScoresImported: number; requestsLast: number; quotaProtected: boolean };
type Payload = { polling: { recommendedPlan: string; plans: Plan[] }; cadence: { firstCheckMinutesAfterKickoff: number; cronIntervalMinutes: number; regularRetryMinutes: number[]; playoffRetryMinutes: number[]; note: string }; scorePolls: Poll[]; ladderSummary: Array<{ rung: number; pickedUp: number; percentage: number }> };

function local(value: string | null) { return value ? new Date(value).toLocaleString("en-US", { timeZone: "America/New_York", hour: "numeric", minute: "2-digit", timeZoneName: "short" }) : "—"; }

export default function PollingStrategyPanel() {
  const [data, setData] = useState<Payload | null>(null);
  useEffect(() => { let active = true; void fetchWithSession("/api/admin/grading-dashboard").then((response) => response.json()).then((payload) => { if (active && payload.polling && payload.cadence && payload.scorePolls) setData(payload); }).catch(() => undefined); return () => { active = false; }; }, []);
  if (!data) return null;
  return <div className="mt-5 space-y-5">
    <div className="border border-zinc-300 bg-white p-4"><div className="flex flex-wrap items-baseline justify-between gap-3"><div><h3 className="font-serif text-xl font-bold">Polling strategy simulator</h3><p className="mt-1 text-sm text-zinc-600">Projected score-provider cost for the current slate. Recommendations are advisory and never change production automatically.</p></div><span className="border border-amber-700 bg-amber-50 px-2 py-1 text-xs font-black uppercase tracking-wide">Approval required</span></div><div className="mt-4 grid gap-3 md:grid-cols-3">{data.polling.plans.map((plan) => <div className={`border p-3 ${plan.id === data.polling.recommendedPlan ? "border-green-700 bg-green-50" : "border-zinc-200"}`} key={plan.id}><div className="flex items-center justify-between gap-2"><p className="font-bold">{plan.label}</p>{plan.id === data.polling.recommendedPlan ? <span className="text-xs font-black uppercase tracking-wide text-green-800">Suggested</span> : null}</div><p className="mt-2 text-sm">{plan.description}</p><dl className="mt-3 space-y-1 text-xs"><div className="flex justify-between gap-2"><dt className="text-zinc-600">Checks / game</dt><dd className="font-semibold">{plan.checksPerGame}</dd></div><div className="flex justify-between gap-2"><dt className="text-zinc-600">This slate</dt><dd className="font-semibold">{plan.periodCredits} credits</dd></div><div className="flex justify-between gap-2"><dt className="text-zinc-600">30-day projection</dt><dd className="font-semibold">{plan.monthlyCredits} credits</dd></div></dl></div>)}</div></div>
    <div className="border border-zinc-300 bg-white p-4"><h3 className="font-serif text-xl font-bold">Current polling cadence</h3><p className="mt-1 text-sm text-zinc-600">{data.cadence.note}</p><div className="mt-4 grid gap-3 sm:grid-cols-3 text-sm"><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">FIRST CHECK</p><p className="mt-1 font-semibold">{Math.floor(data.cadence.firstCheckMinutesAfterKickoff / 60)}h {data.cadence.firstCheckMinutesAfterKickoff % 60}m after kickoff</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">CRON TICK</p><p className="mt-1 font-semibold">Every {data.cadence.cronIntervalMinutes} minutes</p></div><div className="border border-zinc-200 p-3"><p className="text-xs font-black tracking-wide text-zinc-500">RETRY LADDER</p><p className="mt-1 font-semibold">{data.cadence.regularRetryMinutes.join(" · ")}m</p><p className="mt-1 text-xs text-zinc-600">Playoffs: {data.cadence.playoffRetryMinutes.join(" · ")}m</p></div></div>{data.ladderSummary.length ? <div className="mt-4 border-t border-zinc-200 pt-4"><p className="text-sm font-bold">Finals picked up by ladder rung</p><div className="mt-2 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{data.ladderSummary.map((item) => <div className="border border-zinc-200 p-2 text-sm" key={item.rung}><p className="text-xs font-black tracking-wide text-zinc-500">RUNG {item.rung}</p><p className="mt-1 font-semibold">{item.percentage}%</p><p className="text-xs text-zinc-600">{item.pickedUp} game{item.pickedUp === 1 ? "" : "s"}</p></div>)}</div></div> : <p className="mt-4 text-xs text-zinc-500">Ladder pickup percentages will populate as new score polls record their rung.</p>}</div>
    <div className="border border-zinc-300 bg-white p-4"><div className="flex flex-wrap items-baseline justify-between gap-3"><div><h3 className="font-serif text-xl font-bold">Recent score polls</h3><p className="mt-1 text-sm text-zinc-600">Actual worker results, including how many finals each provider check found.</p></div><span className="text-xs font-bold text-zinc-500">Last {data.scorePolls.length}</span></div>{data.scorePolls.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[42rem] text-left text-sm"><thead className="border-b border-zinc-300 text-xs uppercase tracking-wide text-zinc-500"><tr><th className="pb-2 pr-3">Checked</th><th className="pb-2 pr-3">Mode</th><th className="pb-2 pr-3">Eligible</th><th className="pb-2 pr-3">Finals found</th><th className="pb-2 pr-3">Finals saved</th><th className="pb-2">Credits</th></tr></thead><tbody>{data.scorePolls.map((poll) => <tr className="border-b border-zinc-100" key={`${poll.startedAt}-${poll.pollingMode}`}><td className="py-2 pr-3 text-xs text-zinc-600">{local(poll.completedAt ?? poll.startedAt)}</td><td className="py-2 pr-3 font-semibold capitalize">{poll.pollingMode}{poll.quotaProtected ? " · quota held" : ""}</td><td className="py-2 pr-3 tabular-nums">{poll.eligibleGames}</td><td className="py-2 pr-3 tabular-nums">{poll.completedGamesFound}</td><td className="py-2 pr-3 font-semibold tabular-nums">{poll.finalScoresImported}</td><td className="py-2 tabular-nums">{poll.requestsLast}</td></tr>)}</tbody></table></div> : <p className="mt-4 text-sm text-zinc-600">No score polls have been recorded yet.</p>}</div>
  </div>;
}
