// Generates the committed database types (src/lib/database.types.ts) from the isolated test database
// after the current migrations have been applied, and checks that the committed file still matches it.
//
//   npm run db:types          write the file (needs PICKEM_TEST_DATABASE_URL and the Supabase CLI)
//   npm run db:types:check    fail if the committed file differs from the schema
//
// Only the isolated project is ever read, never production, and the same guards as the isolated workflow
// apply. The application build and the fast tests never need this: they type-check the committed file.
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";

const target = fileURLToPath(new URL("../src/lib/database.types.ts", import.meta.url));
const url = process.env.PICKEM_TEST_DATABASE_URL ?? "";
const mode = process.argv[2] === "--check" ? "check" : "write";

if (process.env.PICKEM_TEST_DATABASE_CONFIRMATION !== "isolated" || !url.includes("lrimviwfflrisshmgnsh")) {
  console.error("Refusing to read a database that is not the confirmed isolated test project.");
  process.exit(1);
}

const result = spawnSync("supabase", ["gen", "types", "typescript", "--db-url", url, "--schema", "public"], { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
if (result.status !== 0 || !result.stdout.trim()) {
  console.error("The Supabase CLI could not generate types.");
  console.error((result.stderr || "").replace(/postgres(ql)?:\/\/\S+/g, "[connection string hidden]"));
  process.exit(1);
}

const normalize = (text) => text.replace(/\r\n/g, "\n").trimEnd() + "\n";
const generated = normalize(`// Generated by scripts/database-types.mjs from the isolated database. Do not edit by hand:\n// run \`npm run db:types\` after a migration, or fix the migration.\n${result.stdout}`);

if (mode === "write") {
  writeFileSync(target, generated);
  console.log(`Wrote ${target}`);
} else if (!existsSync(target)) {
  console.error("src/lib/database.types.ts is missing.");
  process.exit(1);
} else if (normalize(readFileSync(target, "utf8")) !== generated) {
  writeFileSync(`${target}.generated`, generated);
  console.error("src/lib/database.types.ts no longer matches the database schema. Regenerate it with `npm run db:types` (the current schema was written next to it as database.types.ts.generated).");
  process.exit(1);
} else {
  console.log("Database types match the schema.");
}
